name: Coverage CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build-gcc9-coveralls:
    runs-on: ubuntu-latest
    name: GNU GCC 9 and run coveralls
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build easy
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=g++-9 -DEASY_TEST=ON -DENABLE_COVERAGE=ON ..
        make run_tests
    - name: Run tests
      run: |
        cd build
        ./test/run_tests "~[quality]"
    - name: Run lcov
      run: |
        sudo apt-get install lcov
        lcov -t "result" -o lcov.info -c -d .
        lcov -e lcov.info "*easy/include*" -o lcov_filtered.info
        lcov -l lcov_filtered.info
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./lcov_filtered.info
