name: Linux CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build-gcc9:
    runs-on: ubuntu-latest
    name: GNU GCC 9
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build mockturtle
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=g++-9 -DEASY_TEST=ON ..
        make run_tests
    - name: Run tests
      run: |
        cd build
        ./test/run_tests "~[quality]"
  build-gcc10:
    runs-on: ubuntu-latest
    name: GNU GCC 10
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build mockturtle
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=g++-10 -DEASY_TEST=ON ..
        make run_tests
    - name: Run tests
      run: |
        cd build
        ./test/run_tests "~[quality]"
  build-gcc12:
    runs-on: ubuntu-latest
    name: GNU GCC 12
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build mockturtle
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=g++-12 -DEASY_TEST=ON ..
        make run_tests
    - name: Run tests
      run: |
        cd build
        ./test/run_tests "~[quality]"
  build-clang11:
    runs-on: ubuntu-20.04
    name: Clang 11
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build mockturtle
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=clang++-11 -DEASY_TEST=ON ..
        make run_tests
    - name: Run tests
      run: |
        cd build
        ./test/run_tests "~[quality]"
  build-clang13:
    runs-on: ubuntu-latest
    name: Clang 13
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build mockturtle
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=clang++-13 -DEASY_TEST=ON ..
        make run_tests
    - name: Run tests
      run: |
        cd build
        ./test/run_tests "~[quality]"
